'use client';

// Airspace zones overlay — loads pre-fetched GeoJSON from /data/airspaces-cz.json
// (generated by scripts/fetch-airspaces.js) and renders colored polygons on the Leaflet map.
// No API call at runtime — data is bundled as a static public file.
// Must be a child of MapContainer (useMapLayer calls useMap internally).

import { airspaceColor, parseAirspaceItems } from '@/lib/airspace';
import { DataRegion, dataFileUrl } from '@/lib/dataRegion';
import { useMapLayer } from '@/hooks/useMapLayer';
import type { GeoJSON } from 'leaflet';

interface AirspaceLayerProps {
  /** Whether to show airspace zones on the map */
  active: boolean;
  dataRegion: DataRegion;
}

export default function AirspaceLayer({ active, dataRegion }: AirspaceLayerProps) {
  useMapLayer({
    active,
    fetchUrl: dataFileUrl('airspaces', dataRegion),

    // Convert { items: unknown[] } → GeoJSON FeatureCollection with color pre-computed
    parseData: (rawData) => {
      const data = rawData as { items?: unknown[] };
      if (!Array.isArray(data.items)) throw new Error('Unexpected data format');
      const zones = parseAirspaceItems(data.items);
      return {
        type: 'FeatureCollection',
        features: zones.map((zone) => ({
          type: 'Feature' as const,
          properties: {
            name:      zone.name,
            typeName:  zone.typeName,
            icaoClass: zone.icaoClass ?? null,
            color:     airspaceColor(zone.type),
          },
          geometry: zone.geometry as GeoJSON.GeometryObject,
        })),
      };
    },

    styleFeature: (feature) => {
      const color = (feature.properties?.color as string) ?? '#94a3b8';
      return { color, weight: 1.5, opacity: 0.9, fillColor: color, fillOpacity: 0.12 };
    },

    tooltipHtml: (props) => {
      const classLabel = props.icaoClass ? ` · třída ${props.icaoClass}` : '';
      return `<strong>${props.name}</strong><br/><span>${props.typeName}${classLabel}</span>`;
    },

    hoverFillOpacity: 0.3,
  });

  return null;
}
